"""Tray icon rendering helpers.

ARCH-003: extracted from tray.py to separate the PIL/image-rendering
logic from the menu/callback logic.
"""

import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any

from voice_typer.server.platform_utils import is_windows
from voice_typer.server.tray_types import AppState

if TYPE_CHECKING:
    from PIL import Image as PilImage

log = logging.getLogger(__name__)


def _get_pil_image():
    """Lazy import of PIL.Image to avoid importing heavy dependencies at module load.

    This also allows tests that mock PIL to work correctly — the module-level
    import would resolve to a mock if a test with mocked PIL imports this
    module first, breaking real_pil tests.
    """
    from PIL import Image

    return Image


def _pil_lanczos() -> int:
    """Return the LANCZOS resampling filter across Pillow versions.

    Pillow 9.1.0 (Mar 2022) moved ``LANCZOS`` from a module-level
    integer to ``Image.Resampling.LANCZOS``.  Pillow 10+ removed the
    module-level alias entirely.  Our pyproject allows Pillow >= 9.0, so
    we resolve the constant at runtime via ``getattr`` (which also
    sidesteps the type-stub difference between Pillow 9 and 10).
    """
    from PIL import Image

    resampling = getattr(Image, "Resampling", None)
    if resampling is not None:
        return int(getattr(resampling, "LANCZOS", 1))
    return int(getattr(Image, "LANCZOS", 1))


# NEW-MEM-003 / NEW-PERF-005: _icon_cache is intentionally process-global.
# It caches rendered PIL Images keyed by (AppState, size).  With 6
# states × 1-2 DPI-aware sizes = ~12 entries, each ~64×64 RGBA = ~16 KB,
# the total footprint is ~200 KB (not 1 MB as the issue estimated).
# The icons are needed for the lifetime of the tray (the whole process),
# so clearing them would just cause re-rendering on every state change
# — the exact overhead NEW-PERF-005 was designed to eliminate.
_icon_cache: dict[tuple[AppState, int], "PilImage.Image"] = {}

# NEW-PERF-005: DPI never changes within a session — cache the result
# of _get_dpi_aware_icon_size() after the first call so we don't run
# Win32 GetDC(0) + GetDeviceCaps + ReleaseDC on every tray state
# change (10–30 ms per state change → 0 ms after the first call).
_dpi_aware_size_cache: "int | None" = None


def _get_dpi_aware_icon_size() -> int:
    """TRAY-020: Query DPI scaling and adjust icon size accordingly.

    NEW-PERF-005: cached after the first call.  DPI never changes
    within a session (the user would have to log out + log back in
    after changing display scaling), so re-querying Win32 on every
    tray state change is pure waste.  The cache is at module level
    because the tray icon renderer is a singleton within the process.
    """
    global _dpi_aware_size_cache
    if _dpi_aware_size_cache is not None:
        return _dpi_aware_size_cache

    base_size = 64
    detected = base_size
    if is_windows():
        try:
            import ctypes

            hdc = ctypes.windll.user32.GetDC(0)
            if hdc:
                dpi = ctypes.windll.gdi32.GetDeviceCaps(hdc, 88)  # LOGPIXELSX
                ctypes.windll.user32.ReleaseDC(0, hdc)
                if dpi > 96:
                    scale = dpi / 96.0
                    detected = int(base_size * scale)
        except Exception:
            log.debug("[TRAY] DPI scaling probe failed", exc_info=True)
    _dpi_aware_size_cache = detected
    return detected


def invalidate_dpi_cache() -> None:
    """Clear the cached DPI-aware icon size.

    Useful in tests that mock ctypes.windll with different DPI values.
    In production, DPI never changes mid-session so this is never
    called.
    """
    global _dpi_aware_size_cache
    _dpi_aware_size_cache = None


def _get_icon_path(state: AppState, size: int = 0) -> Path | None:
    """PLAT-024: Return the path to the appropriate icon file for the state.

    On Windows, prefers ICO format (multiple sizes in one file, sharper
    on Windows 11). On other platforms, returns the PNG path.

    Returns None if no icon file is found.
    """
    if size == 0:
        size = _get_dpi_aware_icon_size()
    asset_dir = Path(__file__).resolve().parent / "assets"

    # PLAT-024: on Windows, prefer .ico files for sharper tray icons.
    # Try state-specific ICO first (tray-mic-{state}.ico), then the
    # base ICO (tray-mic.ico) which is generated by generate-icons.mjs.
    if is_windows():
        ico_path = asset_dir / f"tray-mic-{state.value}.ico"
        if ico_path.exists():
            return ico_path
        # PLAT-024: fall back to the base tray-mic.ico (colorized at
        # runtime per AppState).
        base_ico = asset_dir / "tray-mic.ico"
        if base_ico.exists():
            return base_ico

    # Fallback: use the PNG icon
    available = [16, 24, 32, 48, 64]
    best = min(available, key=lambda x: abs(x - size))
    png_path = asset_dir / f"tray-mic-{best}.png"
    if png_path.exists():
        return png_path
    return None


# PLAT-021 / TRAY-032: Shape definitions for tray icons.
# Icons use BOTH color AND shape to differentiate states, making them
# accessible to color-blind users. When a pre-rendered PNG icon is
# available, the shape is overlaid as a small indicator in the corner.
# When no PNG is found, a shape-only icon is drawn as fallback.
_ICON_SHAPES = {
    AppState.IDLE: "circle",
    AppState.RECORDING: "square",
    AppState.TRANSCRIBING: "diamond",
    AppState.LOADING: "triangle",
    AppState.ERROR: "triangle",
    AppState.CANCELLING: "square",
}


def _draw_shape(shape: str, size: int, color: tuple):
    """TRAY-032: Draw a shape-only icon as fallback when no PNG is available.

    Creates a solid-color shape on a transparent background. Each state
    has a distinct shape (circle, square, diamond, triangle) so that
    color-blind users can differentiate states by shape alone.

    Parameters
    ----------
    shape : str
        One of "circle", "square", "diamond", "triangle".
    size : int
        Icon size in pixels (width = height).
    color : tuple
        RGBA color tuple.

    Returns
    -------
    PIL.Image.Image
        The rendered shape icon.
    """
    from PIL import ImageDraw

    image = _get_pil_image()
    img = image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    margin = max(2, size // 8)
    inner = size - 2 * margin

    if shape == "circle":
        draw.ellipse([margin, margin, margin + inner, margin + inner], fill=color)
    elif shape == "square":
        draw.rectangle([margin, margin, margin + inner, margin + inner], fill=color)
    elif shape == "diamond":
        cx, cy = size // 2, size // 2
        half = inner // 2
        draw.polygon([(cx, cy - half), (cx + half, cy), (cx, cy + half), (cx - half, cy)], fill=color)
    elif shape == "triangle":
        cx = size // 2
        draw.polygon([(cx, margin), (margin + inner, margin + inner), (margin, margin + inner)], fill=color)
    else:
        # Unknown shape — fallback to circle
        draw.ellipse([margin, margin, margin + inner, margin + inner], fill=color)

    return img


def _draw_shape_indicator(img, shape: str, color: tuple):
    """TRAY-032: Overlay a small shape indicator in the bottom-right corner.

    This adds a visible shape marker to the microphone icon so that
    color-blind users can identify the state by shape in addition to color.

    Parameters
    ----------
    img : PIL.Image.Image
        The base microphone icon (already colorized).
    shape : str
        One of "circle", "square", "diamond", "triangle".
    color : tuple
        RGBA color tuple for the indicator.

    Returns
    -------
    PIL.Image.Image
        The icon with a small shape indicator overlay.
    """
    from PIL import ImageDraw

    img = img.copy()
    draw = ImageDraw.Draw(img)
    img_size = img.size
    if not img_size or len(img_size) != 2:
        log.warning("[TRAY] _draw_shape_indicator: image has invalid size %r — skipping indicator overlay", img_size)
        return img  # Can't draw indicator on image without valid size
    w, h = img_size
    ind_size = max(4, w // 5)  # indicator is ~20% of icon size
    x0 = w - ind_size - 1
    y0 = h - ind_size - 1

    if shape == "circle":
        draw.ellipse([x0, y0, x0 + ind_size, y0 + ind_size], fill=color)
    elif shape == "square":
        draw.rectangle([x0, y0, x0 + ind_size, y0 + ind_size], fill=color)
    elif shape == "diamond":
        cx, cy = x0 + ind_size // 2, y0 + ind_size // 2
        half = ind_size // 2
        draw.polygon([(cx, cy - half), (cx + half, cy), (cx, cy + half), (cx - half, cy)], fill=color)
    elif shape == "triangle":
        draw.polygon([(x0 + ind_size // 2, y0), (x0 + ind_size, y0 + ind_size), (x0, y0 + ind_size)], fill=color)

    return img


def _make_icon(state: AppState, size: int = 0):
    """Generate a colored microphone icon based on state.

    Uses pre-rendered white microphone PNG (from logo.svg, rendered by
    ``client/scripts/generate-icons.mjs``) and colorizes it per state.
    TRAY-020: If size is 0, auto-detect DPI.
    NEW-DUP-009: the old ``vt_logo.svg`` reference was stale — that file
    was removed; the source SVG now lives at ``client/scripts/logo.svg``.

    PLAT-021/TRAY-032: Icons use both color AND shape to differentiate
    states. When a PNG microphone icon is available, a small shape
    indicator is overlaid in the bottom-right corner. When no PNG is
    found, a shape-only icon is drawn as fallback (fully accessible
    to color-blind users who can identify states by shape alone).
    """
    if size == 0:
        size = _get_dpi_aware_icon_size()
    cache_key = (state, size)
    if cache_key in _icon_cache:
        return _icon_cache[cache_key]

    # XV-117: on Windows, prefer a pre-built STATE-SPECIFIC .ico when
    # one exists on disk. ``generate-icons.mjs`` produces a colored +
    # shape-indicator-baked .ico per state; loading it directly skips
    # the PNG→ICO re-encode path entirely (faster first-render and a
    # smaller icon-cache footprint). The base ``tray-mic.ico`` is
    # white/uncolored and is intentionally NOT used here — falling
    # through to the PNG synthesis path colorizes it correctly per
    # state. ``_get_icon_path`` returns the state-specific path ONLY
    # when the file exists, so the name comparison is a safe guard.
    if is_windows():
        state_ico_path = _get_icon_path(state, size)
        if state_ico_path is not None and state_ico_path.name == f"tray-mic-{state.value}.ico":
            try:
                pil_img = _get_pil_image()
                pre_built = pil_img.open(str(state_ico_path)).convert("RGBA")
                if pre_built.size != (size, size):
                    pre_built = pre_built.resize((size, size), _pil_lanczos())
                _icon_cache[cache_key] = pre_built
                return pre_built
            except Exception:
                log.debug(
                    "[TRAY] Pre-built state ICO load failed — falling back to PNG synthesis",
                    exc_info=True,
                )

    # PLAT-021/TRAY-006: Color-blind accessible colors.
    # RECORDING: bright green (was red/orange) — clearly distinct from
    #   ERROR red and CANCELLING orange for color-blind users.
    # ERROR: red — keeps the universal "error" association.
    # CANCELLING: orange — distinct from both green and red.
    colors = {
        AppState.IDLE: (120, 120, 120, 255),
        AppState.RECORDING: (46, 204, 113, 255),  # Bright green
        AppState.TRANSCRIBING: (52, 152, 219, 255),
        AppState.LOADING: (243, 156, 18, 255),
        AppState.ERROR: (231, 76, 60, 255),  # Red
        AppState.CANCELLING: (243, 156, 18, 255),  # Orange
    }
    color = colors.get(state, (120, 120, 120, 255))
    shape = _ICON_SHAPES.get(state, "circle")

    png_loaded = False
    # TASK-14: initialize ``pil_img`` and ``colored`` to ``None`` BEFORE
    # the try block so that the downstream code paths (the else branch
    # and the Windows ICO re-encoding) cannot reference an unbound name
    # if the try block exits early. The ``png_loaded`` flag governs
    # whether we use ``colored`` from the try (PNG path) or replace it
    # with the shape fallback, but pyrefly cannot prove that
    # ``png_loaded=True`` implies ``colored is not None``.
    # ``pil_img`` is the ``PIL.Image`` module itself (returned by
    # ``_get_pil_image()``); ``Any`` reflects that there is no
    # first-class ``ModuleType`` stub in scope.
    pil_img: Any | None = None
    colored: Any | None = None
    try:
        asset_dir = Path(__file__).resolve().parent / "assets"
        available = [16, 24, 32, 48, 64]
        best = min(available, key=lambda x: abs(x - size))
        pil_img = _get_pil_image()
        mic_img = pil_img.open(str(asset_dir / f"tray-mic-{best}.png")).convert("RGBA")
        colored = pil_img.new("RGBA", mic_img.size, color)
        # NEW-MEM-004: use getchannel('A') instead of split()[3].
        colored.putalpha(mic_img.getchannel("A"))
        if colored.size != (size, size):
            # TASK-14: PIL 9.1+ moved ``LANCZOS`` to
            # ``Image.Resampling.LANCZOS``; the module-level alias is
            # deprecated and removed from Pillow's type stubs in 10+.
            # ``_pil_lanczos()`` resolves the constant at runtime via
            # ``getattr`` so we work on Pillow >= 9.0 (the floor in
            # pyproject.toml) without type-checker false positives.
            colored = colored.resize((size, size), _pil_lanczos())
        png_loaded = True
    except Exception:
        log.debug("[TRAY] PNG icon load failed — using shape fallback", exc_info=True)

    if not png_loaded:
        # TRAY-032: No PNG icon available — use shape-only fallback
        colored = _draw_shape(shape, size, color)
    else:
        # TRAY-032: PNG loaded — overlay a small shape indicator
        # for color-blind accessibility (shape visible even if color
        # perception is impaired)
        # ``colored`` is guaranteed non-None here because ``png_loaded``
        # is set to True only after ``colored`` is assigned in the try.
        assert colored is not None
        colored = _draw_shape_indicator(colored, shape, color)

    if is_windows() and pil_img is not None and colored is not None:
        # PLAT-024: Save as ICO format for Windows tray.
        # ICO supports multiple sizes (16, 32, 48) and is the
        # native format for Windows tray icons — sharper than PNG on
        # Windows 11 with per-monitor DPI scaling.
        #
        # XV-116: the 256×256 plane was previously included for
        # "completeness" but Windows tray never requests it — the
        # shell's NIM_GETICON queries cap out at 48×48 (or 64×64 on
        # high-DPI). Each 256×256 RGBA plane is ~256 KB in the ICO
        # buffer, so caching it across 6 states × DPI sizes inflated
        # the icon cache by ~1.5 MB avoidably. Dropping it cuts the
        # ICO footprint by ~75% with no visual change.
        try:
            import io

            ico_buf = io.BytesIO()
            colored.save(ico_buf, format="ICO", sizes=[(16, 16), (32, 32), (48, 48)])
            ico_buf.seek(0)
            colored = pil_img.open(ico_buf)
        except Exception:
            log.debug("[TRAY] PIL ICO conversion failed — using PNG", exc_info=True)

    # TASK-14: ``colored`` is guaranteed non-None at this point —
    # either the try block produced a PIL image (and we asserted that
    # above), or the ``not png_loaded`` branch assigned the shape
    # fallback.  Assert once more so pyrefly narrows ``Optional[Any]``
    # to ``Any`` for the cache assignment below.
    assert colored is not None
    _icon_cache[cache_key] = colored
    return colored
