//! Tauri command handler modules (ADR-0020 §6 + §7 + §10 + MIG-1.1 + MIG-1.2).

pub(crate) mod sidecar_cmds;
pub(crate) mod export;
pub(crate) mod bubble;

// Re-export the command functions so `tauri::generate_handler!` in `main.rs`
// can find both the functions AND the helper macros (`__cmd__<name>` etc.)
// generated by the `#[tauri::command]` attribute. Without these re-exports,
// `generate_handler!` fails with "cannot find macro `__cmd__<name>`".
//
// `#[allow(unused_imports)]` silences the false-positive warning — these
// are referenced by the `tauri::generate_handler!` macro expansion, which
// the lint pass cannot see.
#[allow(unused_imports)]
pub use sidecar_cmds::{dispatch, paste_text, shutdown_sidecar};
#[allow(unused_imports)]
pub use export::{export_history, export_vocabulary};
#[allow(unused_imports)]
pub use bubble::{
    bubble_hide_complete, bubble_move_by, bubble_set_draggable, bubble_set_position,
    bubble_show, bubble_signal_ready,
};
