"""MIG-1.6 Phase 0-M Gate Check 2 — externalBin spawn validation (macOS).

This module is gate check 2 of 9 for Phase 0-M (the macOS Tauri cutover
gate). It validates the Tauri sidecar spawn path that the Rust host uses
to launch the frozen Python sidecar via Tauri's ``externalBin`` mechanism
on **both** macOS archs (Apple Silicon + Intel).

Scope of this check (ADR-0020 §1 + §4.1 + §7 + §10 + §13.2 + §14):

1. ``tauri.conf.json`` declares ``externalBin: ["bin/python-sidecar"]``
   (Tauri appends the Rust target triple at runtime — see ADR-0020 §7
   "externalBin per-arch naming" + §4.1). The shipped binaries on disk
   are ``src-tauri/bin/python-sidecar-x86_64-apple-darwin`` (Intel) and
   ``src-tauri/bin/python-sidecar-aarch64-apple-darwin`` (Apple Silicon).

2. ``tauri.conf.json`` ships the macOS native binary
   (``macos-key-listener``, built by ``scripts/build/compile_native.sh``
   via ``swiftc -O``) and the macOS prewarm binaries for both
   ``x86_64-apple-darwin`` + ``aarch64-apple-darwin`` target triples as
   ``bundle.resources``. Per ADR-0020 §5, the prewarm helper is a
   ``bundle.resource`` (NOT ``externalBin``) because it is launched by
   the macOS LaunchAgent, NOT spawned by Tauri.

3. ``src-tauri/src/sidecar/spawn.rs`` reads the ``server_started`` JSON
   line from the sidecar's stdout via ``tauri_plugin_shell``'s
   ``CommandEvent::Stdout`` stream and parses the port. (The auth token
   is generated by the Rust host and passed to the sidecar via the
   ``VOICE_TYPER_IPC_TOKEN`` env var at spawn — it is NOT echoed back
   in the ``server_started`` payload. See ADR-0020 §3 + §1.)

4. The release-path spawn (``spawn_sidecar_release``) is **cross-platform**
   — it calls ``app.shell().sidecar("python-sidecar")`` which goes
   through Tauri's shell plugin. There is NO ``cfg!(target_os = "macos")``
   branch in the release spawn path: macOS uses the **same spawn code**
   as Windows + Linux. (The dev-mode path in ``spawn_sidecar_dev_mode``
   DOES use ``cfg!(target_os = "windows")`` to pick ``python.exe`` vs
   ``python3``, and ``prewarm_resource_path`` uses ``cfg!(windows)`` for
   the ``.exe`` suffix — those are NOT the release spawn path.)

5. The FT-1 crash supervisor (in ``src-tauri/src/sidecar/ft1.rs``, backed
   by constants in ``src-tauri/src/util.rs``) restarts the sidecar on
   crash with a doubling backoff schedule
   ``[500ms, 1s, 2s, 4s, 8s]`` (task's "500ms → 8s" range) and a cap of
   5 retries before falling back to a full-app ``app.restart()``
   (ADR-0020 §10). The schedule length equals the cap.

6. The sidecar binds ``127.0.0.1:0`` (loopback + ephemeral port) and
   writes the OS-assigned port to stdout — the host NEVER chooses a
   fixed port. (ADR-0020 §1 "Ephemeral port — locked bind direction".)

7. The tests in this file do NOT spawn any real process — they read
   the Rust source files + JSON config as text and assert on their
   contents. No ``subprocess.Popen`` / ``os.exec*`` /
   ``tauri::AppHandle`` is constructed. The ``tauri::AppHandle`` /
   ``tauri_plugin_shell::ShellExt`` APIs are mocked by treating them
   as opaque — we only verify the source code wires them correctly.

VALIDATE ON MACOS HOST:
    This file is the Linux-sandbox half of gate check 2. The other
    half MUST be executed by a human on a real macOS host (BOTH Apple
    Silicon AND Intel) — ADR-0020 §6 / runbook §6.1. Steps:

    1. Build sidecar (see check 1) for the host arch
       (``python-sidecar-aarch64-apple-darwin`` on Apple Silicon,
        ``python-sidecar-x86_64-apple-darwin`` on Intel).
    2. ``cd src-tauri; cargo tauri build --target x86_64-apple-darwin``
       (OR ``aarch64-apple-darwin``; OR ``universal-apple-darwin`` for
       a universal .app that ships both arches).
    3. Open ``target/<arch>/release/bundle/dmg/*.dmg`` → drag to
       Applications (or ``hdiutil attach`` + ``cp -R`` to script it).
    4. Launch "Voice Typer" from Applications (first launch will prompt
       for Accessibility + Microphone permission — grant both via
       System Settings → Privacy & Security).
    5. Within 30 s, check
       ``~/Library/Logs/voice-typer/voice-typer.log`` for:
       - ``[SIDECAR] server_started port=XXXXX``
         (where XXXXX is an OS-assigned ephemeral port, e.g. 51234)
       - ``[SIDECAR-WS] listening on 127.0.0.1:XXXXX`` (sidecar log)
    6. ``ps aux | grep python-sidecar`` — must show the sidecar process
       matching the host arch (``python-sidecar-aarch64-apple-darwin``
       on Apple Silicon, ``python-sidecar-x86_64-apple-darwin`` on
       Intel).
    Expected: sidecar spawns within 2 s; log shows ``server_started``
    with an ephemeral port (1024-65535, NOT a fixed port like 9876).
    Fail scenarios:
      - ``failed to resolve sidecar binary`` → the host-arch
        ``python-sidecar-<arch>-apple-darwin`` is missing from
        ``src-tauri/bin/`` (run §1 of the runbook for the missing arch).
      - ``sidecar did not emit server_started within 30000ms`` →
        sidecar crashed on import (CTranslate2 wheel ABI mismatch on
        aarch64, or stdout block-buffered under Tauri's pipe).
      - macOS Gatekeeper blocks the .app → run
        ``xattr -dr com.apple.quarantine "/Applications/Voice Typer.app"``
        for local dev, OR sign + notarize per runbook §7.

    See ``docs/migration/macos-validation-runbook.md`` §5 (gate point 1)
    + §6.1 (gate point 2) for the full pass criteria + fail-scenario
    triage.

References:
- ADR-0020 §1 — ephemeral port + locked bind direction + the
  ``server_started`` stdout handshake.
- ADR-0020 §4.1 — per-arch ``externalBin`` binary naming (Tauri appends
  the Rust target triple at runtime via ``std::env::consts::ARCH`` +
  ``std::env::consts::OS``).
- ADR-0020 §5 — prewarm is a ``bundle.resource`` (NOT ``externalBin``)
  because it is launched by the macOS LaunchAgent, not by Tauri.
- ADR-0020 §7 — Tauri config + capabilities + ``externalBin`` list.
- ADR-0020 §10 — FT-1 supervisor backoff schedule + cap (5 retries,
  doubling 500ms → 8s, then ``app.restart()``).
- ADR-0020 §13.2 — macOS code-signing + notarization (out of scope for
  this spawn-path check, but the gate points downstream depend on it).
- ADR-0020 §14 — dev-mode spawn fallback (out of scope for this macOS
  release-path check, but verified as a code path).
- runbook §5 (gate point 1) — host-side validation commands for the
  externalBin spawn.
- runbook §6.1 (gate point 2) — WS + HMAC handshake validation.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

# ─── Repo path resolution ──────────────────────────────────────────────
# Tests run from the repo root, but we resolve every path relative to
# this file's location so the tests pass regardless of cwd.
_THIS_FILE = Path(__file__).resolve()
# parents[0]=mig16, [1]=tauri, [2]=tests, [3]=voice-typer (repo root)
_REPO_ROOT = _THIS_FILE.parents[3]
_SRC_TAURI = _REPO_ROOT / "src-tauri"
_TAURI_CONF = _SRC_TAURI / "tauri.conf.json"
_SPAWN_RS = _SRC_TAURI / "src" / "sidecar" / "spawn.rs"
_FT1_RS = _SRC_TAURI / "src" / "sidecar" / "ft1.rs"
_UTIL_RS = _SRC_TAURI / "src" / "util.rs"
_MAIN_RS = _SRC_TAURI / "src" / "main.rs"
_SIDECAR_WS_PY = _REPO_ROOT / "voice_typer" / "server" / "sidecar_ws.py"


# ─── Shared fixtures ───────────────────────────────────────────────────


@pytest.fixture(scope="module")
def tauri_conf() -> dict:
    """Load + parse src-tauri/tauri.conf.json."""
    assert _TAURI_CONF.exists(), f"tauri.conf.json not found: {_TAURI_CONF}"
    return json.loads(_TAURI_CONF.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def spawn_rs_source() -> str:
    """Read src-tauri/src/sidecar/spawn.rs as text (for static assertions)."""
    assert _SPAWN_RS.exists(), f"spawn.rs not found: {_SPAWN_RS}"
    return _SPAWN_RS.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def spawn_rs_release_section() -> str:
    """Slice of spawn.rs containing only ``spawn_sidecar_release``.

    Used to assert the release-path spawn is cross-platform (no
    ``cfg!(target_os = ...)`` / ``cfg_attr`` platform branch).
    """
    src = _SPAWN_RS.read_text(encoding="utf-8")
    start = src.find("fn spawn_sidecar_release")
    assert start != -1, "spawn_sidecar_release not found in spawn.rs"
    # Slice to the next top-level `pub(crate) async fn` / `pub(crate) fn`
    # / `pub fn` / `fn ` (whichever comes first AFTER the start).
    next_fn_match = re.search(
        r"\n(?:pub(?:\(crate\))?\s+)?(?:async\s+)?fn\s+\w+",
        src[start + 1 :],
    )
    end = (start + 1 + next_fn_match.start()) if next_fn_match else len(src)
    return src[start:end]


@pytest.fixture(scope="module")
def ft1_rs_source() -> str:
    """Read src-tauri/src/sidecar/ft1.rs as text."""
    assert _FT1_RS.exists(), f"ft1.rs not found: {_FT1_RS}"
    return _FT1_RS.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def util_rs_source() -> str:
    """Read src-tauri/src/util.rs as text (for the FT-1 constants)."""
    assert _UTIL_RS.exists(), f"util.rs not found: {_UTIL_RS}"
    return _UTIL_RS.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def main_rs_source() -> str:
    """Read src-tauri/src/main.rs as text."""
    assert _MAIN_RS.exists(), f"main.rs not found: {_MAIN_RS}"
    return _MAIN_RS.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def sidecar_ws_source() -> str:
    """Read voice_typer/server/sidecar_ws.py as text (for the bind address)."""
    assert _SIDECAR_WS_PY.exists(), f"sidecar_ws.py not found: {_SIDECAR_WS_PY}"
    return _SIDECAR_WS_PY.read_text(encoding="utf-8")


# ─── Test 1: tauri.conf.json externalBin list ──────────────────────────


def test_tauri_conf_external_bin_lists_python_sidecar(tauri_conf) -> None:
    """ADR-0020 §4.1 + §7: externalBin must list ``bin/python-sidecar``.

    Tauri v2's ``externalBin`` mechanism appends the Rust target triple
    at runtime, so the JSON entry is the binary base name (no triple
    suffix, no ``.exe``). On macOS the shipped binaries on disk are
    ``src-tauri/bin/python-sidecar-aarch64-apple-darwin`` (Apple Silicon)
    and ``src-tauri/bin/python-sidecar-x86_64-apple-darwin`` (Intel) —
    Tauri picks the right one at runtime via
    ``std::env::consts::ARCH`` + ``std::env::consts::OS``.
    """
    bundle = tauri_conf.get("bundle", {})
    assert "externalBin" in bundle, "bundle.externalBin must exist"
    external_bin = bundle["externalBin"]
    assert isinstance(external_bin, list), "externalBin must be a list"
    assert "bin/python-sidecar" in external_bin, (
        "externalBin must contain 'bin/python-sidecar' (Tauri appends the target triple at spawn time)"
    )
    # The list must NOT contain any triple-suffixed entries — the base
    # name is what the Rust `app.shell().sidecar("python-sidecar")` call
    # in spawn.rs uses, and Tauri internally appends the triple.
    for entry in external_bin:
        assert not re.search(
            r"-x86_64-apple-darwin"
            r"|-aarch64-apple-darwin"
            r"|-x86_64-pc-windows-msvc"
            r"|-aarch64-pc-windows-msvc"
            r"|-x86_64-unknown-linux-gnu"
            r"|-aarch64-unknown-linux-gnu",
            entry,
        ), (
            f"externalBin entry '{entry}' must NOT contain the target "
            f"triple — Tauri appends it at runtime. Use the base name "
            f"only (e.g. 'bin/python-sidecar')."
        )


def test_tauri_conf_shell_scope_allows_python_sidecar(tauri_conf) -> None:
    """ADR-0020 §7: the shell capability must scope spawn to the sidecar.

    Tauri v2 rejects an unconstrained ``shell:allow-spawn``; the
    capability must name the sidecar binary by its base name. This is
    the same on macOS as on Windows — Tauri's shell plugin is
    cross-platform.
    """
    shell = tauri_conf.get("plugins", {}).get("shell", {})
    assert shell.get("sidecar") is True, "plugins.shell.sidecar must be true to enable the externalBin API"
    scope = shell.get("scope", [])
    assert isinstance(scope, list) and scope, "plugins.shell.scope must be a non-empty list"
    # At least one scope entry must name bin/python-sidecar with sidecar=true.
    matches = [s for s in scope if s.get("name") == "bin/python-sidecar" and s.get("sidecar") is True]
    assert matches, (
        "plugins.shell.scope must include "
        "{'name': 'bin/python-sidecar', 'sidecar': true} "
        "(Tauri v2 requires explicit spawn scoping)"
    )


# ─── Test 2: macOS native + prewarm resources ─────────────────────────


def test_tauri_conf_resources_include_macos_native(tauri_conf) -> None:
    """ADR-0020 §4.1 + §6.4: macos-key-listener must be a resource.

    The native hotkey binary is spawned by the Python sidecar (NOT by
    Tauri), so it must be a ``bundle.resource`` extracted to
    ``resourceDir/native/`` and discovered by the sidecar via the
    ``VOICE_TYPER_NATIVE_DIR`` env var (ADR-0020 §6.4 + §4.1).

    On macOS the binary is built by ``scripts/build/compile_native.sh``
    via ``swiftc -O`` with Cocoa + CoreGraphics (see runbook §3 + ADR-0008).
    The file name has NO arch suffix (Tauri's resource extraction
    preserves the source-tree name verbatim).
    """
    resources = tauri_conf.get("bundle", {}).get("resources", [])
    assert isinstance(resources, list) and resources, "bundle.resources must be a non-empty list"
    assert "resources/native/macos-key-listener" in resources, (
        "bundle.resources must include 'resources/native/macos-key-listener' "
        "for macOS hotkey support (ADR-0020 §6.4, swiftc-compiled per §0008)"
    )


@pytest.mark.parametrize(
    "triple",
    [
        "aarch64-apple-darwin",
        "x86_64-apple-darwin",
    ],
)
def test_tauri_conf_resources_include_macos_prewarm(tauri_conf, triple: str) -> None:
    """ADR-0020 §4.1 + §5: per-arch prewarm binaries for macOS.

    The prewarm binary is launched by the macOS LaunchAgent (NOT by
    Tauri), so it must be a ``bundle.resource`` extracted to
    ``resourceDir``. Tauri's ``externalBin`` is NOT used for prewarm.
    One binary per macOS target triple (aarch64 + x86_64).
    """
    resources = tauri_conf.get("bundle", {}).get("resources", [])
    expected = f"resources/prewarm-{triple}"
    assert expected in resources, (
        f"bundle.resources must include '{expected}' (per-arch prewarm binary for macOS {triple}, ADR-0020 §5)"
    )


# ─── Test 3: spawn.rs target_triple_for() — Apple Silicon + Intel ─────


def test_spawn_rs_target_triple_for_apple_silicon(spawn_rs_source) -> None:
    """ADR-0020 §4.1: ``target_triple_for("aarch64", "macos")`` → Apple Silicon.

    The pure predicate ``target_triple_for(arch, os)`` in spawn.rs must
    return ``"aarch64-apple-darwin"`` for Apple Silicon Macs. Tauri's
    ``externalBin`` resolver appends this exact string to the base name
    ``python-sidecar`` to find the binary at
    ``src-tauri/bin/python-sidecar-aarch64-apple-darwin``.
    """
    # The match arm for ("aarch64", "macos") → "aarch64-apple-darwin".
    assert re.search(
        r'\(\s*"aarch64"\s*,\s*"macos"\s*\)\s*=>\s*"aarch64-apple-darwin"\.into\(\)',
        spawn_rs_source,
    ), (
        'spawn.rs::target_triple_for must map ("aarch64", "macos") → '
        '"aarch64-apple-darwin" (Tauri externalBin suffix for Apple Silicon)'
    )


def test_spawn_rs_target_triple_for_intel(spawn_rs_source) -> None:
    """ADR-0020 §4.1: ``target_triple_for("x86_64", "macos")`` → Intel.

    The pure predicate ``target_triple_for(arch, os)`` in spawn.rs must
    return ``"x86_64-apple-darwin"`` for Intel Macs. Tauri's
    ``externalBin`` resolver appends this exact string to the base name
    ``python-sidecar`` to find the binary at
    ``src-tauri/bin/python-sidecar-x86_64-apple-darwin``.
    """
    assert re.search(
        r'\(\s*"x86_64"\s*,\s*"macos"\s*\)\s*=>\s*"x86_64-apple-darwin"\.into\(\)',
        spawn_rs_source,
    ), (
        'spawn.rs::target_triple_for must map ("x86_64", "macos") → '
        '"x86_64-apple-darwin" (Tauri externalBin suffix for Intel Macs)'
    )


def test_spawn_rs_current_target_triple_uses_runtime_arch_os(
    spawn_rs_source,
) -> None:
    """ADR-0020 §4.1: ``current_target_triple`` reads runtime arch + os.

    The host's actual target triple is computed at runtime from
    ``std::env::consts::ARCH`` + ``std::env::consts::OS`` — this is the
    pair Tauri's ``externalBin`` resolver uses to pick the right binary
    name suffix. On macOS the host arch is either ``aarch64`` (Apple
    Silicon) or ``x86_64`` (Intel), and the OS is ``macos``.
    """
    assert "std::env::consts::ARCH" in spawn_rs_source, (
        "current_target_triple must read std::env::consts::ARCH at runtime "
        "(Tauri uses the same source for externalBin per-arch resolution)"
    )
    assert "std::env::consts::OS" in spawn_rs_source, (
        "current_target_triple must read std::env::consts::OS at runtime "
        "(Tauri uses the same source for externalBin per-arch resolution)"
    )
    # current_target_triple must delegate to target_triple_for (the pure form).
    assert re.search(
        r"fn\s+current_target_triple\s*\(\s*\)\s*->\s*String\s*\{[^}]*"
        r"target_triple_for\s*\(\s*std::env::consts::ARCH\s*,\s*"
        r"std::env::consts::OS\s*\)",
        spawn_rs_source,
        re.DOTALL,
    ), "current_target_triple must delegate to target_triple_for with std::env::consts::ARCH + std::env::consts::OS"


# ─── Test 4: spawn.rs reads server_started JSON from stdout ────────────


def test_spawn_rs_calls_shell_sidecar_with_base_name(spawn_rs_source) -> None:
    """ADR-0020 §4.1: spawn.rs resolves the sidecar by base name.

    The Rust code calls ``app.shell().sidecar("python-sidecar")`` —
    the tauri-plugin-shell API appends the target triple internally
    (so the binary file on disk is ``python-sidecar-<triple>`` but the
    API call uses only the base name). This is the SAME call on macOS,
    Windows, and Linux — Tauri's shell plugin is cross-platform.
    """
    assert re.search(
        r'\.sidecar\s*\(\s*"python-sidecar"\s*\)',
        spawn_rs_source,
    ), 'spawn.rs must call `app.shell().sidecar("python-sidecar")` (tauri-plugin-shell appends the target triple)'


def test_spawn_rs_reads_command_event_stdout(spawn_rs_source) -> None:
    """ADR-0020 §1: spawn.rs consumes the CommandEvent::Stdout stream.

    The tauri-plugin-shell ``spawn()`` returns a
    ``Receiver<CommandEvent>``; spawn.rs must match on
    ``CommandEvent::Stdout(bytes)`` to read the ``server_started`` line.
    On macOS the stdout stream is the same pipe abstraction as on
    Windows — there is no platform branch.
    """
    assert "CommandEvent::Stdout" in spawn_rs_source, (
        "spawn.rs must match CommandEvent::Stdout to read sidecar stdout "
        "(tauri-plugin-shell API, not std::process::Stdio::piped)"
    )
    assert "CommandEvent::Stderr" in spawn_rs_source, (
        "spawn.rs must also match CommandEvent::Stderr (logs but doesn't parse)"
    )
    assert "CommandEvent::Terminated" in spawn_rs_source, (
        "spawn.rs must match CommandEvent::Terminated to detect pre-handshake crash"
    )


def test_spawn_rs_parses_port_from_server_started(spawn_rs_source) -> None:
    """ADR-0020 §1: spawn.rs parses the port from the server_started JSON.

    The sidecar writes ONE line to stdout:
        ``{"event":"server_started","port":<n>}``
    and spawn.rs must parse the ``port`` field. The auth token is NOT
    in this payload — it was generated by the Rust host and passed to
    the sidecar via the ``VOICE_TYPER_IPC_TOKEN`` env var at spawn
    (ADR-0020 §3 + §1). The sidecar never echoes the token back.
    """
    assert "fn parse_server_started" in spawn_rs_source, (
        "spawn.rs must define `parse_server_started(line: &str) -> Option<u16>`"
    )
    assert re.search(
        r'parse_server_started.*?"server_started"',
        spawn_rs_source,
        re.DOTALL,
    ), "parse_server_started must check event == 'server_started'"
    assert '"port"' in spawn_rs_source, "parse_server_started must read the 'port' field from the JSON"


def test_spawn_rs_sets_ipc_token_env_var(spawn_rs_source) -> None:
    """ADR-0020 §3 + §4.1: spawn.rs passes VOICE_TYPER_IPC_TOKEN at spawn.

    The Rust host generates the 256-bit bearer token and passes it to
    the sidecar via env var. The sidecar validates incoming WS auth
    frames against this env var with ``hmac.compare_digest``. This env
    var injection is cross-platform — same on macOS + Windows + Linux.
    """
    assert re.search(
        r'\.env\s*\(\s*"VOICE_TYPER_IPC_TOKEN"\s*,',
        spawn_rs_source,
    ), (
        'spawn.rs must call .env("VOICE_TYPER_IPC_TOKEN", token) on the '
        "sidecar builder to pass the bearer token (ADR-0020 §3)"
    )
    assert re.search(
        r'\.env\s*\(\s*"TAURI_SIDECAR"\s*,\s*"1"\s*\)',
        spawn_rs_source,
    ), (
        "spawn.rs must set TAURI_SIDECAR=1 so the sidecar skips its "
        "Python-side single-instance mutex + heartbeat watchdog"
    )
    assert re.search(
        r'\.env\s*\(\s*"VOICE_TYPER_NATIVE_DIR"\s*,',
        spawn_rs_source,
    ), "spawn.rs must set VOICE_TYPER_NATIVE_DIR to resourceDir/native"
    assert re.search(
        r'\.env\s*\(\s*"VOICE_TYPER_PREWARM_EXE"\s*,',
        spawn_rs_source,
    ), "spawn.rs must set VOICE_TYPER_PREWARM_EXE to the per-arch prewarm binary"


def test_spawn_rs_passes_ws_arg(spawn_rs_source) -> None:
    """ADR-0020 §1: spawn.rs passes ``--ws`` so the sidecar uses WS transport."""
    assert re.search(r'\.args\s*\(\s*\["--ws"\]\s*\)', spawn_rs_source), (
        "spawn.rs must pass --ws to the sidecar so it binds the WS server instead of using the legacy stdio transport"
    )


def test_spawn_rs_server_started_log_line_format(spawn_rs_source) -> None:
    """ADR-0020 §1 + §3: the server_started log line must NOT include the token.

    Per ADR-0020 §3 ("never logged"), the bearer token must not appear
    in any log line. spawn.rs logs ``[SIDECAR] server_started port={}``
    — port only, never the token. The token is rotated per launch and
    per FT-1 respawn and is only ever held in-memory in the Rust host.
    """
    port_log_re = re.compile(r"\[SIDECAR\]\s*server_started\s*port=\{[^}]*\}")
    assert port_log_re.search(spawn_rs_source), (
        "spawn.rs must log '[SIDECAR] server_started port={}' on success "
        "(runbook §5 pass criteria greps for this line on macOS)"
    )
    assert not re.search(
        r"log::\w+!\([^)]*token[^)]*\)",
        spawn_rs_source,
        re.IGNORECASE,
    ), "spawn.rs must NOT log the bearer token — ADR-0020 §3 'never logged'. The token is passed via env var only."


# ─── Test 5: macOS uses the SAME spawn path as Windows (no branch) ────


def test_spawn_rs_release_path_has_no_platform_branch(
    spawn_rs_release_section,
) -> None:
    """ADR-0020 §4.1: the release spawn path is cross-platform.

    ``spawn_sidecar_release`` must NOT contain a
    ``cfg!(target_os = "macos")`` / ``cfg!(target_os = "windows")`` /
    ``cfg!(target_os = "linux")`` / ``cfg_attr`` platform branch —
    macOS uses the **same** spawn code as Windows + Linux via Tauri's
    shell plugin (``app.shell().sidecar("python-sidecar")`` +
    ``CommandEvent::Stdout``). The per-arch binary selection happens
    inside the Tauri shell plugin (which reads ``std::env::consts::ARCH``
    + ``std::env::consts::OS``), NOT in spawn.rs.

    This test slices the source to ONLY the ``spawn_sidecar_release``
    function body so the dev-mode branch (which DOES use
    ``cfg!(target_os = "windows")`` for ``python.exe`` vs ``python3``)
    and ``prewarm_resource_path`` (which uses ``cfg!(windows)`` for the
    ``.exe`` suffix) do NOT trip the assertion.
    """
    # No target_os cfg! branches inside the release spawn path.
    assert not re.search(
        r'cfg!\s*\(\s*target_os\s*=\s*"(?:macos|windows|linux)"\s*\)',
        spawn_rs_release_section,
    ), (
        "spawn_sidecar_release must NOT branch on target_os — the Tauri "
        "shell plugin handles per-arch + per-OS resolution internally. "
        "macOS uses the same spawn path as Windows + Linux."
    )
    # No cfg_attr platform attributes (e.g. #[cfg_attr(target_os = ...)]).
    assert not re.search(
        r"cfg_attr\s*\(\s*target_os\s*=",
        spawn_rs_release_section,
    ), (
        "spawn_sidecar_release must NOT contain cfg_attr(target_os = ...) — "
        "no platform-specific attributes on the release spawn path."
    )
    # The release path must use the shell plugin's cross-platform API.
    assert "app.shell().sidecar" in spawn_rs_release_section or re.search(
        r"\.shell\s*\(\s*\)\s*\.sidecar",
        spawn_rs_release_section,
    ), "spawn_sidecar_release must call app.shell().sidecar(...) — the cross-platform Tauri shell plugin API"


def test_spawn_rs_release_path_does_not_use_std_command(spawn_rs_source, main_rs_source) -> None:
    """The release path must use tauri-plugin-shell, NOT std::process::Command.

    The tauri-plugin-shell ``CommandEvent`` API is the ONLY way to
    spawn an ``externalBin`` sidecar in Tauri v2 — using
    ``std::process::Command`` directly would bypass the
    ``shell:allow-spawn`` capability check and break the per-arch
    binary resolution. This is the same on macOS as on Windows.
    """
    assert "ShellExt" in spawn_rs_source, (
        "spawn.rs must `use tauri_plugin_shell::ShellExt;` to access app.shell().sidecar(...)"
    )
    # The dev-mode path MAY use tokio::process::Command (that's
    # intentional — dev mode bypasses externalBin for fast UI iteration,
    # ADR-0020 §14). But the release path must NOT use std::process.
    assert "fn spawn_sidecar_release" in spawn_rs_source, (
        "spawn.rs must define `spawn_sidecar_release` (the externalBin path)"
    )
    assert "CommandEvent>" in spawn_rs_source, (
        "spawn_sidecar_release must return a Receiver<CommandEvent> (the tauri-plugin-shell event stream)"
    )


# ─── Test 6: FT-1 crash supervisor (backoff 500ms → 8s, cap 5) ────────


def test_ft1_backoff_constants(util_rs_source) -> None:
    """ADR-0020 §10: FT-1 supervisor backoff schedule + cap (macOS = same).

    The schedule is a doubling series starting at 500 ms and capped at
    5 retries before falling back to a full-app ``app.restart()``.
    The full schedule is ``[500, 1000, 2000, 4000, 8000]`` — i.e.
    ``500ms → 1s → 2s → 4s → 8s`` (the task's "500ms → 8s" range).
    The schedule is the SAME on macOS as on Windows — there is no
    per-platform FT-1 config.
    """
    backoff_re = re.compile(r"(?:pub\s*\(\s*crate\s*\)\s*)?const\s+FT1_BACKOFF_MS\s*:\s*&\[u64\]\s*=\s*&\[([^\]]+)\]")
    m = backoff_re.search(util_rs_source)
    assert m, "util.rs must define `const FT1_BACKOFF_MS: &[u64] = &[...]`"
    steps = [int(x.strip()) for x in m.group(1).split(",") if x.strip()]
    # First step must be 500 ms (ADR-0020 §10 + runbook §6.1).
    assert steps[0] == 500, f"FT1_BACKOFF_MS[0] must be 500 (got {steps[0]}); ADR-0020 §10 schedule starts at 500 ms"
    # The schedule must include an 8000 ms (8s) step (task's "8s" cap).
    assert 8000 in steps, (
        f"FT1_BACKOFF_MS must include an 8000 ms step (got {steps}); task specifies '500ms → 8s' range"
    )
    # Doubling property — each step is 2x the previous.
    for i in range(1, len(steps)):
        assert steps[i] == steps[i - 1] * 2, (
            f"FT1_BACKOFF_MS[{i}] must be 2x [{i - 1}] "
            f"(got {steps[i]} vs {steps[i - 1]}); ADR-0020 §10 doubling schedule"
        )


def test_ft1_max_retries_is_5(util_rs_source) -> None:
    """ADR-0020 §10: FT-1 retry cap must be 5 before full-app relaunch."""
    cap_re = re.compile(r"(?:pub\s*\(\s*crate\s*\)\s*)?const\s+FT1_MAX_RETRIES\s*:\s*u32\s*=\s*(\d+)")
    m = cap_re.search(util_rs_source)
    assert m, "util.rs must define `const FT1_MAX_RETRIES: u32 = N`"
    cap = int(m.group(1))
    assert cap == 5, f"FT1_MAX_RETRIES must be 5 (got {cap}); ADR-0020 §10 cap"


def test_ft1_backoff_schedule_length_matches_cap(util_rs_source) -> None:
    """The backoff schedule length must equal the retry cap.

    Each retry attempts one spawn; the schedule provides the per-attempt
    delay. If the schedule is shorter than the cap, the loop body would
    index out of bounds. If longer, the extra steps are unreachable.
    """
    backoff_re = re.compile(r"const\s+FT1_BACKOFF_MS\s*:\s*&\[u64\]\s*=\s*&\[([^\]]+)\]")
    cap_re = re.compile(r"const\s+FT1_MAX_RETRIES\s*:\s*u32\s*=\s*(\d+)")
    m_back = backoff_re.search(util_rs_source)
    m_cap = cap_re.search(util_rs_source)
    assert m_back and m_cap, "FT1 constants must be defined in util.rs"
    steps = [int(x.strip()) for x in m_back.group(1).split(",") if x.strip()]
    cap = int(m_cap.group(1))
    assert len(steps) == cap, (
        f"FT1_BACKOFF_MS.len() ({len(steps)}) must equal FT1_MAX_RETRIES ({cap}) so the loop iterates exactly N times"
    )


def test_ft1_respawn_calls_spawn_sidecar(ft1_rs_source) -> None:
    """ADR-0020 §10: ft1_respawn must call spawn_sidecar_and_get_port.

    The FT-1 supervisor in ``ft1.rs`` is the loop that retries on
    crash; it calls back into ``spawn.rs``'s spawn function each
    iteration. The two modules together implement the crash-supervisor
    contract (spawn → on crash → backoff → respawn). This is the same
    on macOS as on Windows — the FT-1 supervisor is platform-agnostic.
    """
    assert "fn ft1_respawn" in ft1_rs_source, "ft1.rs must define `ft1_respawn` (the supervisor entry point)"
    assert "spawn_sidecar_and_get_port" in ft1_rs_source, (
        "ft1.rs must call `spawn_sidecar_and_get_port` to respawn (the FT-1 supervisor delegates spawn to spawn.rs)"
    )
    assert "ft1_relaunching" in ft1_rs_source, (
        "ft1.rs must emit 'ft1_relaunching' event before app.restart() (ADR-0020 §10 UI banner)"
    )
    assert "ft1_reconnected" in ft1_rs_source, (
        "ft1.rs must emit 'ft1_reconnected' on successful respawn (so the UI can clear the 'reconnecting…' banner)"
    )


def test_ft1_respawn_serializes_with_atomic_flag(ft1_rs_source) -> None:
    """ADR-0020 §10: FT-1 must serialize concurrent respawn attempts.

    If the WS reader and the stdout reader both detect a crash
    simultaneously, only ONE respawn may run (the other bails out).
    This is enforced via a ``respawn_in_progress`` atomic flag with
    a compare_exchange.
    """
    assert "respawn_in_progress" in ft1_rs_source, (
        "ft1.rs must use a `respawn_in_progress` atomic flag to serialize concurrent respawn attempts (ADR-0020 §10)"
    )
    assert "compare_exchange" in ft1_rs_source, (
        "ft1.rs must use compare_exchange on the respawn_in_progress flag to atomically claim the respawn slot"
    )


# ─── Test 7: ephemeral 127.0.0.1:0 port (no fixed port) ───────────────


def test_sidecar_ws_binds_loopback_ephemeral_port(sidecar_ws_source) -> None:
    """ADR-0020 §1: sidecar binds 127.0.0.1:0 — OS assigns the port.

    The sidecar must NEVER bind a fixed port (the legacy 9876). The
    OS assigns a free ephemeral port at bind time, and the sidecar
    writes that port to stdout for the host to read. This eliminates
    the EADDRINUSE race + the exit-code-10 respawn dance — same
    behavior on macOS as on Windows.
    """
    assert re.search(
        r'_LOOPBACK_HOST\s*=\s*"127\.0\.0\.1"',
        sidecar_ws_source,
    ), "sidecar_ws.py must define _LOOPBACK_HOST = '127.0.0.1' (hard loopback — no 0.0.0.0/:: bind, ADR-0020 §1)"
    assert re.search(
        r"serve\s*\(\s*_handler\s*,\s*_LOOPBACK_HOST\s*,\s*0\s*",
        sidecar_ws_source,
    ), "sidecar_ws.py must call serve(handler, _LOOPBACK_HOST, 0) — port 0 means OS-assigned ephemeral (ADR-0020 §1)"
    assert not re.search(r"bind\s*\([^)]*9876", sidecar_ws_source), (
        "sidecar_ws.py must NOT bind the legacy fixed port 9876 — ADR-0020 §1 mandates ephemeral :0"
    )


def test_sidecar_ws_emits_server_started_with_port(sidecar_ws_source) -> None:
    """ADR-0020 §1: sidecar writes the OS-assigned port to stdout JSON.

    After ``serve(...)`` binds 127.0.0.1:0, the sidecar reads back the
    actual port via ``ws_server.sockets[0].getsockname()[1]`` and
    emits ``{"event":"server_started","port":<n>}`` to stdout (the
    ONLY thing that ever goes to stdout).
    """
    assert "def _emit_server_started" in sidecar_ws_source, "sidecar_ws.py must define _emit_server_started(port: int)"
    assert re.search(
        r'json\.dumps\s*\(\s*\{\s*"event"\s*:\s*"server_started"\s*,\s*"port"\s*:',
        sidecar_ws_source,
    ), '_emit_server_started must emit {"event":"server_started","port":<n>} (matches spawn.rs::parse_server_started)'
    assert "getsockname" in sidecar_ws_source, (
        "sidecar_ws.py must read the OS-assigned port via "
        "ws_server.sockets[0].getsockname()[1] — never assume a fixed port"
    )


def test_spawn_rs_does_not_hardcode_port(spawn_rs_source) -> None:
    """ADR-0020 §1: the Rust host must NOT choose or hardcode the port.

    The host reads the port from the sidecar's stdout; it never
    pre-allocates a port or probes for one. This eliminates the
    TOCTOU race the legacy fixed-port design had.
    """
    assert not re.search(r"TcpListener::bind", spawn_rs_source), (
        "spawn.rs must NOT bind a TCP listener — the sidecar is the WS server, the host is the WS client (ADR-0020 §1)"
    )
    release_section = spawn_rs_source
    if "fn spawn_sidecar_release" in release_section:
        start = release_section.index("fn spawn_sidecar_release")
        release_section = release_section[start:]
    assert "parse_server_started" in release_section, (
        "spawn_sidecar_release must obtain the port by calling parse_server_started on a stdout line"
    )


# ─── Test 8: no real process spawn (mocked AppHandle/ShellExt) ────────


def test_this_test_file_does_not_spawn_processes() -> None:
    """This test file must NOT spawn any real process.

    The Tauri ``AppHandle`` / ``tauri_plugin_shell::ShellExt`` APIs
    are mocked by treating them as opaque: the tests above only read
    the Rust source code as text and assert on its contents. No
    ``subprocess.Popen``, ``os.exec*``, ``os.system``, ``os.spawn*``,
    or ``tauri::AppHandle`` is constructed at runtime.

    We use ``ast`` to parse this file and assert no ``Call`` node
    invokes any forbidden process-spawning API. (String literals in
    docstrings / forbidden_apis lists are NOT calls — the AST check
    avoids false positives on the docstring examples above.)
    """
    import ast

    this_source = _THIS_FILE.read_text(encoding="utf-8")
    tree = ast.parse(this_source)

    forbidden_call_names = {
        ("subprocess", "Popen"),
        ("subprocess", "run"),
        ("subprocess", "call"),
        ("subprocess", "check_call"),
        ("subprocess", "check_output"),
        ("os", "system"),
        ("os", "popen"),
        ("os", "spawnl"),
        ("os", "spawnle"),
        ("os", "spawnlp"),
        ("os", "spawnlpe"),
        ("os", "spawnv"),
        ("os", "spawnve"),
        ("os", "spawnvp"),
        ("os", "spawnvpe"),
        ("os", "execl"),
        ("os", "execle"),
        ("os", "execlp"),
        ("os", "execlpe"),
        ("os", "execv"),
        ("os", "execve"),
        ("os", "execvp"),
        ("os", "execvpe"),
    }

    def _qualified(node: ast.AST) -> tuple[str, ...] | None:
        """Return the dotted call target of `node`, or None."""
        if isinstance(node, ast.Attribute):
            base = _qualified(node.value)
            if base is None:
                return None
            return base + (node.attr,)
        if isinstance(node, ast.Name):
            return (node.id,)
        return None

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        target = _qualified(node.func)
        if target is None:
            continue
        for forbidden in forbidden_call_names:
            if tuple(target[-len(forbidden) :]) == forbidden:
                pytest.fail(
                    f"This test file must NOT call {'.'.join(forbidden)}() — "
                    f"the tauri::AppHandle / tauri_plugin_shell APIs are "
                    f"mocked by static source inspection. No real sidecar "
                    f"process may be spawned in the sandbox."
                )


def test_spawn_rs_uses_app_handle_not_concrete_process(spawn_rs_source) -> None:
    """The release-path spawn takes a ``&tauri::AppHandle`` (mockable).

    spawn_sidecar_release's signature is
    ``(app: &tauri::AppHandle, token: &str) -> Result<...>``. The
    ``AppHandle`` is a trait object that can be substituted with a
    mock in Rust unit tests (e.g. via ``mockall`` or a test double).
    The function does NOT directly construct a ``std::process::Command``
    — it goes through ``app.shell().sidecar(...).spawn()`` which is
    the mockable plugin boundary.
    """
    assert re.search(
        r"fn\s+spawn_sidecar_release\s*\(\s*app\s*:\s*&tauri::AppHandle",
        spawn_rs_source,
    ), (
        "spawn_sidecar_release must take `app: &tauri::AppHandle` as the "
        "first arg (mockable plugin boundary, not a concrete process)"
    )
    assert re.search(
        r"fn\s+spawn_sidecar_and_get_port\s*\(\s*app\s*:\s*&tauri::AppHandle",
        spawn_rs_source,
    ), "spawn_sidecar_and_get_port must take `app: &tauri::AppHandle` (the public entry point)"


# ─── Test 9 (bonus): dev-mode fallback path is wired (ADR-0020 §14) ───


def test_spawn_rs_has_dev_mode_fallback(spawn_rs_source) -> None:
    """ADR-0020 §14: spawn.rs must have a dev-mode fallback path.

    When ``VOICE_TYPER_SIDECAR_DEV=1`` is set, the host spawns
    ``python -m voice_typer.server.ipc_server --ws`` via
    ``tokio::process::Command`` instead of the frozen externalBin.
    This lets UI/transport iterate in seconds (no Nuitka recompile)
    during dev. The release path (this gate check's scope) is the
    frozen-exe path; the dev path is verified here only as a code
    branch that exists. On macOS dev mode the Python binary is
    ``python3`` (NOT ``python.exe``).
    """
    assert "fn is_dev_mode" in spawn_rs_source, (
        "spawn.rs must define `is_dev_mode()` to check VOICE_TYPER_SIDECAR_DEV=1"
    )
    assert "fn spawn_sidecar_dev_mode" in spawn_rs_source, (
        "spawn.rs must define `spawn_sidecar_dev_mode` for the dev fallback"
    )
    assert "tokio::process::Command" in spawn_rs_source, (
        "spawn_sidecar_dev_mode must use tokio::process::Command (not the "
        "tauri-plugin-shell) — dev mode bypasses externalBin"
    )
    assert re.search(
        r'cfg!\s*\(\s*target_os\s*=\s*"windows"\s*\)',
        spawn_rs_source,
    ), (
        'spawn_sidecar_dev_mode must use cfg!(target_os = "windows") to '
        "pick python.exe on Windows vs python3 on macOS/Linux"
    )


# ─── Test 10 (bonus): server_started timeout matches ADR-0020 §1 ──────


def test_server_started_timeout_is_30s(util_rs_source) -> None:
    """ADR-0020 §1: the host waits up to 30 s for server_started.

    The sidecar must emit the ``server_started`` JSON within 30 s of
    spawn — if it doesn't, the host kills the child and reports the
    failure (runbook §5 fail-scenario: "sidecar did not emit
    server_started within 30000ms"). This is the same timeout on
    macOS as on Windows.
    """
    timeout_re = re.compile(r"const\s+SERVER_STARTED_TIMEOUT_MS\s*:\s*u64\s*=\s*([\d_]+)")
    m = timeout_re.search(util_rs_source)
    assert m, "util.rs must define SERVER_STARTED_TIMEOUT_MS"
    timeout_ms = int(m.group(1).replace("_", ""))
    assert timeout_ms == 30_000, (
        f"SERVER_STARTED_TIMEOUT_MS must be 30000 (30 s), got {timeout_ms}; "
        f"ADR-0020 §1 + runbook §5 fail-scenario message"
    )
