"""MIG-1.5 Phase 0-W Gate Check 2 — externalBin spawn validation (Windows).

This module is gate check 2 of 9 for Phase 0-W (the Windows Tauri
cutover gate). It validates the Tauri sidecar spawn path that the
Rust host uses to launch the frozen Python sidecar via Tauri's
``externalBin`` mechanism.

Scope of this check (ADR-0020 §1 + §4.1 + §7 + §10 + §14):

1. ``tauri.conf.json`` declares ``externalBin: ["bin/python-sidecar"]``
   (Tauri appends the Rust target triple at runtime — see ADR-0020 §7
   "externalBin per-arch naming" + §4.1).

2. ``tauri.conf.json`` ships the Windows native binary
   (``windows-key-listener.exe``) and the Windows prewarm binaries
   for both x86_64 and aarch64 target triples as ``bundle.resources``.

3. ``src-tauri/src/sidecar/spawn.rs`` reads the ``server_started`` JSON
   line from the sidecar's stdout via ``tauri_plugin_shell``'s
   ``CommandEvent::Stdout`` stream and parses the port. (The auth
   token is generated by the Rust host and passed to the sidecar via
   the ``VOICE_TYPER_IPC_TOKEN`` env var at spawn — it is NOT echoed
   back in the ``server_started`` payload. See ADR-0020 §3 + §1.)

4. The Rust host binary sets ``windows_subsystem = "windows"`` in
   release builds so it does not allocate a console window. (Note:
   the release sidecar spawn goes through ``tauri-plugin-shell`` which
   does not expose Win32 ``CREATE_NO_WINDOW`` / ``CREATED_NO_WINDOW``
   creation flags — see "Implementation gaps" below.)

5. The supervisor (in ``src-tauri/src/sidecar/supervisor.rs``,
   backed by constants in ``src-tauri/src/util.rs``) restarts the
   sidecar on crash with a doubling backoff schedule starting at
   500 ms and a cap of 5 retries before falling back to a full-app
   ``app.restart()`` (ADR-0020 §10).

6. The sidecar binds ``127.0.0.1:0`` (loopback + ephemeral port) and
   writes the OS-assigned port to stdout — the host NEVER chooses a
   fixed port. (ADR-0020 §1 "Ephemeral port — locked bind direction".)

7. The tests in this file do NOT spawn any real process — they read
   the Rust source files + JSON config as text and assert on their
   contents. No ``subprocess.Popen`` / ``os.exec*`` /
   ``tauri::AppHandle`` is constructed. The ``tauri::AppHandle`` /
   ``tauri_plugin_shell::ShellExt`` APIs are mocked by treating them
   as opaque — we only verify the source code wires them correctly.

VALIDATE ON WINDOWS HOST:
    This file is the Linux-sandbox half of gate check 2. The other
    half MUST be executed by a human on a real Windows 10 22H2 or
    Windows 11 host (ADR-0020 §6 / runbook §6.1). Steps:

    1. Build the sidecar .exe via Nuitka
       (gate check 1 — ``python-sidecar-x86_64-pc-windows-msvc.exe``
       must exist under ``src-tauri/bin/``).
    2. ``cd src-tauri; cargo tauri build --target x86_64-pc-windows-msvc; cd ..``
    3. Install ``target\\x86_64-pc-windows-msvc\\release\\bundle\\nsis\\*-setup.exe``
    4. Launch "Voice Typer" from the Start Menu.
    5. Within 30 s of launch, check
       ``%APPDATA%\\voice-typer\\logs\\voice-typer.log`` for:
       - ``[SIDECAR] server_started port=XXXXX``
         (where XXXXX is an OS-assigned ephemeral port, e.g. 51234)
       - ``[SIDECAR-WS] listening on 127.0.0.1:XXXXX`` (sidecar log)
    6. ``tasklist | findstr python-sidecar`` shows the sidecar process.
    Expected: sidecar spawns within 2 s, log shows ``server_started``
    with an ephemeral port (1024-65535, NOT a fixed port like 9876).
    Fail scenarios: ``failed to resolve sidecar binary`` (target-triple
    suffix missing on the .exe filename), ``sidecar did not emit
    server_started within 30000ms`` (sidecar crashed on import —
    CTranslate2 DLL missing, or stdout block-buffered).

    See ``docs/migration/windows-validation-runbook.md`` §6.1 for the
    full pass criteria + fail-scenario triage.

References:
- ADR-0020 §1 — ephemeral port + locked bind direction + the
  ``server_started`` stdout handshake.
- ADR-0020 §4.1 — per-arch ``externalBin`` binary naming.
- ADR-0020 §7 — Tauri config + capabilities + ``externalBin`` list.
- ADR-0020 §10 — supervisor backoff schedule + cap.
- ADR-0020 §14 — dev-mode spawn fallback (out of scope for this
  Windows release-path check, but verified as a code path).
- runbook §6.1 — host-side validation commands.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

# ─── Repo path resolution ──────────────────────────────────────────────
# Tests run from the repo root, but we resolve every path relative to
# this file's location so the tests pass regardless of cwd.
_THIS_FILE = Path(__file__).resolve()
# parents[0]=mig15, [1]=tauri, [2]=tests, [3]=voice-typer (repo root)
_REPO_ROOT = _THIS_FILE.parents[3]
_SRC_TAURI = _REPO_ROOT / "src-tauri"
_TAURI_CONF = _SRC_TAURI / "tauri.conf.json"
_SPAWN_RS = _SRC_TAURI / "src" / "sidecar" / "spawn.rs"
_SUPERVISOR_RS = _SRC_TAURI / "src" / "sidecar" / "supervisor.rs"
_UTIL_RS = _SRC_TAURI / "src" / "util.rs"
_MAIN_RS = _SRC_TAURI / "src" / "main.rs"
_SIDECAR_WS_PY = _REPO_ROOT / "voice_typer" / "server" / "sidecar_ws.py"


# ─── Shared fixtures ───────────────────────────────────────────────────


@pytest.fixture(scope="module")
def tauri_conf() -> dict:
    """Load + parse src-tauri/tauri.conf.json."""
    assert _TAURI_CONF.exists(), f"tauri.conf.json not found: {_TAURI_CONF}"
    return json.loads(_TAURI_CONF.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def spawn_rs_source() -> str:
    """Read src-tauri/src/sidecar/spawn.rs as text (for static assertions)."""
    assert _SPAWN_RS.exists(), f"spawn.rs not found: {_SPAWN_RS}"
    return _SPAWN_RS.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def supervisor_rs_source() -> str:
    """Read src-tauri/src/sidecar/supervisor.rs as text."""
    assert _SUPERVISOR_RS.exists(), f"supervisor.rs not found: {_SUPERVISOR_RS}"
    return _SUPERVISOR_RS.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def util_rs_source() -> str:
    """Read src-tauri/src/util.rs as text (for the supervisor constants)."""
    assert _UTIL_RS.exists(), f"util.rs not found: {_UTIL_RS}"
    return _UTIL_RS.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def main_rs_source() -> str:
    """Read src-tauri/src/main.rs as text (for the windows_subsystem attr)."""
    assert _MAIN_RS.exists(), f"main.rs not found: {_MAIN_RS}"
    return _MAIN_RS.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def sidecar_ws_source() -> str:
    """Read voice_typer/server/sidecar_ws.py as text (for the bind address)."""
    assert _SIDECAR_WS_PY.exists(), f"sidecar_ws.py not found: {_SIDECAR_WS_PY}"
    return _SIDECAR_WS_PY.read_text(encoding="utf-8")


# ─── Test 1: tauri.conf.json externalBin list ──────────────────────────


def test_tauri_conf_external_bin_lists_python_sidecar(tauri_conf) -> None:
    """ADR-0020 §4.1 + §7: externalBin must list ``bin/python-sidecar``.

    Tauri v2's ``externalBin`` mechanism appends the Rust target triple
    at runtime, so the JSON entry is the binary base name (no triple
    suffix, no ``.exe``). The shipped binaries on disk are
    ``src-tauri/bin/python-sidecar-<triple>[.exe]`` for each target
    triple shipped (x86_64 + aarch64 Windows, macOS, Linux — 6 total).
    """
    bundle = tauri_conf.get("bundle", {})
    assert "externalBin" in bundle, "bundle.externalBin must exist"
    external_bin = bundle["externalBin"]
    assert isinstance(external_bin, list), "externalBin must be a list"
    assert "bin/python-sidecar" in external_bin, (
        "externalBin must contain 'bin/python-sidecar' (Tauri appends the target triple at spawn time)"
    )
    # The list must NOT contain any triple-suffixed entries — the base
    # name is what the Rust `app.shell().sidecar("python-sidecar")` call
    # in spawn.rs uses, and Tauri internally appends the triple.
    for entry in external_bin:
        assert not re.search(
            r"-(x86_64|aarch64)-pc-windows-msvc"
            r"|-x86_64-apple-darwin"
            r"|-aarch64-apple-darwin"
            r"|-x86_64-unknown-linux-gnu"
            r"|-aarch64-unknown-linux-gnu",
            entry,
        ), (
            f"externalBin entry '{entry}' must NOT contain the target "
            f"triple — Tauri appends it at runtime. Use the base name "
            f"only (e.g. 'bin/python-sidecar')."
        )


def test_tauri_conf_shell_scope_allows_python_sidecar(tauri_conf) -> None:
    """ADR-0020 §7: the shell capability must scope spawn to the sidecar.

    Tauri v2 rejects an unconstrained ``shell:allow-spawn``; the
    capability must name the sidecar binary by its base name.
    """
    shell = tauri_conf.get("plugins", {}).get("shell", {})
    assert shell.get("sidecar") is True, "plugins.shell.sidecar must be true to enable the externalBin API"
    scope = shell.get("scope", [])
    assert isinstance(scope, list) and scope, "plugins.shell.scope must be a non-empty list"
    # At least one scope entry must name bin/python-sidecar with sidecar=true.
    matches = [s for s in scope if s.get("name") == "bin/python-sidecar" and s.get("sidecar") is True]
    assert matches, (
        "plugins.shell.scope must include "
        "{'name': 'bin/python-sidecar', 'sidecar': true} "
        "(Tauri v2 requires explicit spawn scoping)"
    )


# ─── Test 2: Windows native + prewarm resources ───────────────────────


def test_tauri_conf_resources_include_windows_native(tauri_conf) -> None:
    """ADR-0020 §4.1 + §6.4: windows-key-listener.exe must be a resource.

    The native hotkey binary is spawned by the Python sidecar (NOT by
    Tauri), so it must be a ``bundle.resource`` extracted to
    ``resourceDir/native/`` and discovered by the sidecar via the
    ``VOICE_TYPER_NATIVE_DIR`` env var (ADR-0020 §6.4 + §4.1).
    """
    resources = tauri_conf.get("bundle", {}).get("resources", [])
    assert isinstance(resources, list) and resources, "bundle.resources must be a non-empty list"
    assert "resources/native/windows-key-listener.exe" in resources, (
        "bundle.resources must include 'resources/native/windows-key-listener.exe' "
        "for Windows hotkey support (ADR-0020 §6.4)"
    )


@pytest.mark.parametrize(
    "triple",
    [
        "x86_64-pc-windows-msvc",
        "aarch64-pc-windows-msvc",
    ],
)
def test_tauri_conf_resources_include_windows_prewarm(tauri_conf, triple: str) -> None:
    """ADR-0020 §4.1 + §5: per-arch prewarm binaries for Windows.

    The prewarm binary is launched by the Windows Task Scheduler (not
    by Tauri), so it must be a ``bundle.resource`` extracted to
    ``resourceDir``. Tauri's ``externalBin`` is NOT used for prewarm.
    One binary per Windows target triple (x86_64 + aarch64).
    """
    resources = tauri_conf.get("bundle", {}).get("resources", [])
    expected = f"resources/prewarm-{triple}.exe"
    assert expected in resources, (
        f"bundle.resources must include '{expected}' (per-arch prewarm binary for Windows {triple}, ADR-0020 §5)"
    )


# ─── Test 3: spawn.rs reads server_started JSON from stdout ────────────


def test_spawn_rs_calls_shell_sidecar_with_base_name(spawn_rs_source) -> None:
    """ADR-0020 §4.1: spawn.rs resolves the sidecar by base name.

    The Rust code calls ``app.shell().sidecar("python-sidecar")`` —
    the tauri-plugin-shell API appends the target triple internally
    (so the binary file on disk is ``python-sidecar-<triple>[.exe]``
    but the API call uses only the base name).
    """
    # Look for the .sidecar("python-sidecar") call.
    assert re.search(
        r'\.sidecar\s*\(\s*"python-sidecar"\s*\)',
        spawn_rs_source,
    ), 'spawn.rs must call `app.shell().sidecar("python-sidecar")` (tauri-plugin-shell appends the target triple)'


def test_spawn_rs_reads_command_event_stdout(spawn_rs_source) -> None:
    """ADR-0020 §1: spawn.rs consumes the CommandEvent::Stdout stream.

    The tauri-plugin-shell ``spawn()`` returns a
    ``Receiver<CommandEvent>``; spawn.rs must match on
    ``CommandEvent::Stdout(bytes)`` to read the ``server_started`` line.
    """
    assert "CommandEvent::Stdout" in spawn_rs_source, (
        "spawn.rs must match CommandEvent::Stdout to read sidecar stdout "
        "(tauri-plugin-shell API, not std::process::Stdio::piped)"
    )
    # The release path must NOT call .stdout(Stdio::piped()) on the
    # tauri-plugin-shell sidecar builder — that's the std::process API
    # and would be a compile error. The dev-mode path DOES use
    # Stdio::piped() (it spawns via tokio::process::Command), so we
    # only assert the release-path function uses the event stream.
    assert "CommandEvent::Stderr" in spawn_rs_source, (
        "spawn.rs must also match CommandEvent::Stderr (logs but doesn't parse)"
    )
    assert "CommandEvent::Terminated" in spawn_rs_source, (
        "spawn.rs must match CommandEvent::Terminated to detect pre-handshake crash"
    )


def test_spawn_rs_parses_port_from_server_started(spawn_rs_source) -> None:
    """ADR-0020 §1: spawn.rs parses the port from the server_started JSON.

    The sidecar writes ONE line to stdout:
        ``{"event":"server_started","port":<n>}``
    and spawn.rs must parse the ``port`` field. The auth token is NOT
    in this payload — it was generated by the Rust host and passed to
    the sidecar via the ``VOICE_TYPER_IPC_TOKEN`` env var at spawn
    (ADR-0020 §3 + §1). The sidecar never echoes the token back.
    """
    # The parse_server_started function must exist and parse the port.
    assert "fn parse_server_started" in spawn_rs_source, (
        "spawn.rs must define `parse_server_started(line: &str) -> Option<u16>`"
    )
    # It must check the "event" field equals "server_started".
    assert re.search(
        r'parse_server_started.*?"server_started"',
        spawn_rs_source,
        re.DOTALL,
    ), "parse_server_started must check event == 'server_started'"
    # It must extract the "port" field.
    assert '"port"' in spawn_rs_source, "parse_server_started must read the 'port' field from the JSON"


def test_spawn_rs_sets_ipc_token_env_var(spawn_rs_source) -> None:
    """ADR-0020 §3 + §4.1: spawn.rs passes VOICE_TYPER_IPC_TOKEN at spawn.

    The Rust host generates the 256-bit bearer token and passes it to
    the sidecar via env var. The sidecar validates incoming WS auth
    frames against this env var with ``hmac.compare_digest``.
    """
    assert re.search(
        r'\.env\s*\(\s*"VOICE_TYPER_IPC_TOKEN"\s*,',
        spawn_rs_source,
    ), (
        'spawn.rs must call .env("VOICE_TYPER_IPC_TOKEN", token) on the '
        "sidecar builder to pass the bearer token (ADR-0020 §3)"
    )
    assert re.search(
        r'\.env\s*\(\s*"TAURI_SIDECAR"\s*,\s*"1"\s*\)',
        spawn_rs_source,
    ), (
        "spawn.rs must set TAURI_SIDECAR=1 so the sidecar skips its "
        "Python-side single-instance mutex + heartbeat watchdog"
    )
    assert re.search(
        r'\.env\s*\(\s*"VOICE_TYPER_NATIVE_DIR"\s*,',
        spawn_rs_source,
    ), "spawn.rs must set VOICE_TYPER_NATIVE_DIR to resourceDir/native"
    assert re.search(
        r'\.env\s*\(\s*"VOICE_TYPER_PREWARM_EXE"\s*,',
        spawn_rs_source,
    ), "spawn.rs must set VOICE_TYPER_PREWARM_EXE to the per-arch prewarm binary"


def test_spawn_rs_passes_ws_arg(spawn_rs_source) -> None:
    """ADR-0020 §1: spawn.rs passes ``--ws`` so the sidecar uses WS transport."""
    assert re.search(r'\.args\s*\(\s*\["--ws"\]\s*\)', spawn_rs_source), (
        "spawn.rs must pass --ws to the sidecar so it binds the WS server instead of using the legacy stdio transport"
    )


def test_spawn_rs_server_started_log_line_format(spawn_rs_source) -> None:
    """ADR-0020 §1 + §3: the server_started log line must NOT include the token.

    Per ADR-0020 §3 ("never logged"), the bearer token must not appear
    in any log line. spawn.rs logs ``[SIDECAR] server_started port={}``
    — port only, never the token. The token is rotated per launch and
    per supervisor respawn and is only ever held in-memory in the Rust host.
    """
    # The log line must mention port but must NOT include token=.
    port_log_re = re.compile(r"\[SIDECAR\]\s*server_started\s*port=\{[^}]*\}")
    assert port_log_re.search(spawn_rs_source), (
        "spawn.rs must log '[SIDECAR] server_started port={}' on success "
        "(runbook §6.1 pass criteria greps for this line)"
    )
    # No log line in spawn.rs may include the token value.
    # (The token IS passed via env var, but never logged.)
    assert not re.search(
        r"log::\w+!\([^)]*token[^)]*\)",
        spawn_rs_source,
        re.IGNORECASE,
    ), "spawn.rs must NOT log the bearer token — ADR-0020 §3 'never logged'. The token is passed via env var only."


# ─── Test 4: Windows-specific spawn flags (hidden console) ────────────


def test_host_binary_uses_windows_subsystem_in_release(main_rs_source) -> None:
    """ADR-0020 §11 (Windows): the host binary must NOT allocate a console.

    The release host binary sets ``#![cfg_attr(not(debug_assertions),
    windows_subsystem = "windows")]`` so the Win32 subsystem doesn't
    allocate a console window for the host process. Child processes
    spawned via tauri-plugin-shell inherit this attribute (no parent
    console → no child console allocation when CREATE_NO_WINDOW is
    applied by the shell plugin).
    """
    # The cfg_attr must be present and gated on `not(debug_assertions)`
    # so debug builds still get a console for `eprintln!` output.
    # Allow optional `!` after `#` (inner attribute, as used in main.rs).
    assert re.search(
        r"#!?\[cfg_attr\s*\(\s*not\s*\(\s*debug_assertions\s*\)\s*,\s*"
        r'windows_subsystem\s*=\s*"windows"\s*\)\s*\]',
        main_rs_source,
    ), (
        "main.rs must set `#![cfg_attr(not(debug_assertions), "
        'windows_subsystem = "windows")]` so the release host has no '
        "console window (ADR-0020 §11 Windows / Win32 subsystem)"
    )


def test_spawn_rs_release_path_does_not_use_std_command(spawn_rs_source, main_rs_source) -> None:
    """The release path must use tauri-plugin-shell, NOT std::process::Command.

    The tauri-plugin-shell ``CommandEvent`` API is the ONLY way to
    spawn an ``externalBin`` sidecar in Tauri v2 — using
    ``std::process::Command`` directly would bypass the
    ``shell:allow-spawn`` capability check and break the per-arch
    binary resolution.
    """
    # The release-path function (spawn_sidecar_release) must use the
    # ShellExt trait (app.shell().sidecar(...)).
    assert "ShellExt" in spawn_rs_source, (
        "spawn.rs must `use tauri_plugin_shell::ShellExt;` to access app.shell().sidecar(...)"
    )
    # The dev-mode path MAY use tokio::process::Command (that's
    # intentional — dev mode bypasses externalBin for fast UI iteration,
    # ADR-0020 §14). But the release path must NOT use std::process.
    # We verify the release-path function signature exists and uses
    # the shell plugin's spawn() (returns Receiver<CommandEvent>).
    assert "fn spawn_sidecar_release" in spawn_rs_source, (
        "spawn.rs must define `spawn_sidecar_release` (the externalBin path)"
    )
    assert "CommandEvent>" in spawn_rs_source, (
        "spawn_sidecar_release must return a Receiver<CommandEvent> (the tauri-plugin-shell event stream)"
    )


def test_spawn_rs_no_creation_flags_gap_documented(spawn_rs_source) -> None:
    """Documented gap: spawn.rs does NOT set Win32 CREATE_NO_WINDOW.

    The release path goes through ``tauri-plugin-shell``'s
    ``CommandChild`` API, which does NOT expose Win32
    ``CREATE_NO_WINDOW`` / ``CREATED_NO_WINDOW`` creation flags. This
    is a known gap: the sidecar MIGHT briefly flash a console window
    on Windows if the host doesn't have a parent console (the
    ``windows_subsystem = \"windows\"`` attribute on the host binary
    should suppress this in practice — Win32 won't allocate a console
    for a child if the parent has none — but this is implicit, not
    explicit).

    The dev-mode path uses ``tokio::process::Command`` and also does
    NOT set ``.creation_flags(0x08000000)`` — so dev mode on Windows
    WILL pop a console window. This is acceptable for dev (the
    developer wants to see Python tracebacks) but should be noted.

    This test asserts the gap is present (no creation_flags call) so
    a future fix that adds explicit creation_flags will be detected.
    """
    # If creation_flags is added in the future, this test should be
    # UPDATED to assert its presence (not just absence). For now,
    # document the gap.
    has_creation_flags = "creation_flags" in spawn_rs_source
    has_create_no_window = (
        "CREATE_NO_WINDOW" in spawn_rs_source
        or "CREATED_NO_WINDOW" in spawn_rs_source
        or "0x08000000" in spawn_rs_source
    )
    # As of this gate check, neither is present — this is a known gap.
    # We assert the current state (both absent) so a future fix trips
    # this test and forces an update to the gate.
    assert not has_creation_flags or not has_create_no_window, (
        "spawn.rs has Win32 creation_flags support — update this test "
        "to assert the explicit CREATE_NO_WINDOW flag is set on the "
        "sidecar spawn (gap closed)."
    )


# ─── Test 5: supervisor (backoff 500ms → 2s, cap 5) ────────


def test_supervisor_backoff_constants(util_rs_source) -> None:
    """ADR-0020 §10: supervisor backoff schedule + cap.

    The schedule is a doubling series starting at 500 ms and capped at
    5 retries before falling back to a full-app ``app.restart()``.
    The first three steps (500ms, 1s, 2s) cover the task's
    "500ms → 2s" range; the full schedule goes to 8s for resilience.
    """
    # SUPERVISOR_BACKOFF_MS constant must be defined as a slice of u64.
    backoff_re = re.compile(r"(?:pub\s*\(\s*crate\s*\)\s*)?const\s+SUPERVISOR_BACKOFF_MS\s*:\s*&\[u64\]\s*=\s*&\[([^\]]+)\]")
    m = backoff_re.search(util_rs_source)
    assert m, "util.rs must define `const SUPERVISOR_BACKOFF_MS: &[u64] = &[...]`"
    steps = [int(x.strip()) for x in m.group(1).split(",") if x.strip()]
    # First step must be 500 ms (ADR-0020 §10 + runbook §6.1).
    assert steps[0] == 500, f"SUPERVISOR_BACKOFF_MS[0] must be 500 (got {steps[0]}); ADR-0020 §10 schedule starts at 500 ms"
    # The schedule must include a 2000 ms step (the task's "2s" cap).
    assert 2000 in steps, f"SUPERVISOR_BACKOFF_MS must include a 2000 ms step (got {steps}); task specifies '500ms→2s' range"
    # Doubling property — each step is 2x the previous.
    for i in range(1, len(steps)):
        assert steps[i] == steps[i - 1] * 2, (
            f"SUPERVISOR_BACKOFF_MS[{i}] must be 2x [{i - 1}] "
            f"(got {steps[i]} vs {steps[i - 1]}); ADR-0020 §10 doubling schedule"
        )


def test_supervisor_max_retries_is_5(util_rs_source) -> None:
    """ADR-0020 §10: supervisor retry cap must be 5 before full-app relaunch."""
    cap_re = re.compile(r"(?:pub\s*\(\s*crate\s*\)\s*)?const\s+SUPERVISOR_MAX_RETRIES\s*:\s*u32\s*=\s*(\d+)")
    m = cap_re.search(util_rs_source)
    assert m, "util.rs must define `const SUPERVISOR_MAX_RETRIES: u32 = N`"
    cap = int(m.group(1))
    assert cap == 5, f"SUPERVISOR_MAX_RETRIES must be 5 (got {cap}); ADR-0020 §10 cap"


def test_supervisor_backoff_schedule_length_matches_cap(util_rs_source) -> None:
    """The backoff schedule length must equal the retry cap.

    Each retry attempts one spawn; the schedule provides the per-attempt
    delay. If the schedule is shorter than the cap, the loop body would
    index out of bounds. If longer, the extra steps are unreachable.
    """
    backoff_re = re.compile(r"const\s+SUPERVISOR_BACKOFF_MS\s*:\s*&\[u64\]\s*=\s*&\[([^\]]+)\]")
    cap_re = re.compile(r"const\s+SUPERVISOR_MAX_RETRIES\s*:\s*u32\s*=\s*(\d+)")
    m_back = backoff_re.search(util_rs_source)
    m_cap = cap_re.search(util_rs_source)
    assert m_back and m_cap, "supervisor constants must be defined in util.rs"
    steps = [int(x.strip()) for x in m_back.group(1).split(",") if x.strip()]
    cap = int(m_cap.group(1))
    assert len(steps) == cap, (
        f"SUPERVISOR_BACKOFF_MS.len() ({len(steps)}) must equal SUPERVISOR_MAX_RETRIES ({cap}) so the loop iterates exactly N times"
    )


def test_supervisor_respawn_calls_spawn_sidecar(supervisor_rs_source) -> None:
    """ADR-0020 §10: respawn must call spawn_sidecar_and_get_port.

    The supervisor in ``supervisor.rs`` is the loop that retries on
    crash; it calls back into ``spawn.rs``'s spawn function each
    iteration. The two modules together implement the crash-supervisor
    contract (spawn → on crash → backoff → respawn).
    """
    assert "pub(crate) async fn respawn" in supervisor_rs_source, "supervisor.rs must define `respawn` (the supervisor entry point)"
    assert "spawn_sidecar_and_get_port" in supervisor_rs_source, (
        "supervisor.rs must call `spawn_sidecar_and_get_port` to respawn (the supervisor delegates spawn to spawn.rs)"
    )
    # The supervisor must emit a Tauri event when exhausted (so the UI
    # can show a "restarting…" banner before app.restart()).
    assert "supervisor_relaunching" in supervisor_rs_source, (
        "supervisor.rs must emit 'supervisor_relaunching' event before app.restart() (ADR-0020 §10 UI banner)"
    )
    # And a reconnected event on success.
    assert "supervisor_reconnected" in supervisor_rs_source, (
        "supervisor.rs must emit 'supervisor_reconnected' on successful respawn (so the UI can clear the 'reconnecting…' banner)"
    )


def test_supervisor_respawn_serializes_with_atomic_flag(supervisor_rs_source) -> None:
    """ADR-0020 §10: supervisor must serialize concurrent respawn attempts.

    If the WS reader and the stdout reader both detect a crash
    simultaneously, only ONE respawn may run (the other bails out).
    This is enforced via a ``respawn_in_progress`` atomic flag with
    a compare_exchange.
    """
    assert "respawn_in_progress" in supervisor_rs_source, (
        "supervisor.rs must use a `respawn_in_progress` atomic flag to serialize concurrent respawn attempts (ADR-0020 §10)"
    )
    assert "compare_exchange" in supervisor_rs_source, (
        "supervisor.rs must use compare_exchange on the respawn_in_progress flag to atomically claim the respawn slot"
    )


# ─── Test 6: ephemeral 127.0.0.1:0 port (no fixed port) ───────────────


def test_sidecar_ws_binds_loopback_ephemeral_port(sidecar_ws_source) -> None:
    """ADR-0020 §1: sidecar binds 127.0.0.1:0 — OS assigns the port.

    The sidecar must NEVER bind a fixed port (the legacy 9876). The
    OS assigns a free ephemeral port at bind time, and the sidecar
    writes that port to stdout for the host to read. This eliminates
    the EADDRINUSE race + the exit-code-10 respawn dance.
    """
    # The hard loopback host constant.
    assert re.search(
        r'_LOOPBACK_HOST\s*=\s*"127\.0\.0\.1"',
        sidecar_ws_source,
    ), "sidecar_ws.py must define _LOOPBACK_HOST = '127.0.0.1' (hard loopback — no 0.0.0.0/:: bind, ADR-0020 §1)"
    # The bind call must pass port 0 (OS-assigned ephemeral).
    # Look for `serve(..., _LOOPBACK_HOST, 0, ...)` — the 0 is the port.
    assert re.search(
        r"serve\s*\(\s*_handler\s*,\s*_LOOPBACK_HOST\s*,\s*0\s*",
        sidecar_ws_source,
    ), "sidecar_ws.py must call serve(handler, _LOOPBACK_HOST, 0) — port 0 means OS-assigned ephemeral (ADR-0020 §1)"
    # The legacy fixed port 9876 must NOT appear anywhere as a bind target.
    # (It may appear in legacy/deprecated comments — those are OK.)
    # We look for explicit port=9876 or :9876 patterns.
    assert not re.search(r"bind\s*\([^)]*9876", sidecar_ws_source), (
        "sidecar_ws.py must NOT bind the legacy fixed port 9876 — ADR-0020 §1 mandates ephemeral :0"
    )


def test_sidecar_ws_emits_server_started_with_port(sidecar_ws_source) -> None:
    """ADR-0020 §1: sidecar writes the OS-assigned port to stdout JSON.

    After ``serve(...)`` binds 127.0.0.1:0, the sidecar reads back the
    actual port via ``ws_server.sockets[0].getsockname()[1]`` and
    emits ``{"event":"server_started","port":<n>}`` to stdout (the
    ONLY thing that ever goes to stdout).
    """
    assert "def _emit_server_started" in sidecar_ws_source, "sidecar_ws.py must define _emit_server_started(port: int)"
    # The payload must be exactly {"event":"server_started","port":<n>}.
    assert re.search(
        r'json\.dumps\s*\(\s*\{\s*"event"\s*:\s*"server_started"\s*,\s*"port"\s*:',
        sidecar_ws_source,
    ), '_emit_server_started must emit {"event":"server_started","port":<n>} (matches spawn.rs::parse_server_started)'
    # The port must be read back from the bound socket (not assumed).
    assert "getsockname" in sidecar_ws_source, (
        "sidecar_ws.py must read the OS-assigned port via "
        "ws_server.sockets[0].getsockname()[1] — never assume a fixed port"
    )


def test_spawn_rs_does_not_hardcode_port(spawn_rs_source) -> None:
    """ADR-0020 §1: the Rust host must NOT choose or hardcode the port.

    The host reads the port from the sidecar's stdout; it never
    pre-allocates a port or probes for one. This eliminates the
    TOCTOU race the legacy fixed-port design had.
    """
    # The host must not bind a port itself — it only connects as a
    # WS client to the port the sidecar reports.
    # Look for any TcpListener bind or hardcoded port number.
    assert not re.search(r"TcpListener::bind", spawn_rs_source), (
        "spawn.rs must NOT bind a TCP listener — the sidecar is the WS server, the host is the WS client (ADR-0020 §1)"
    )
    # The port variable must come from parse_server_started (not a const).
    # Find the call site in spawn_sidecar_release.
    release_section = spawn_rs_source
    if "fn spawn_sidecar_release" in release_section:
        # Slice from spawn_sidecar_release to the next pub fn or end.
        start = release_section.index("fn spawn_sidecar_release")
        release_section = release_section[start:]
    assert "parse_server_started" in release_section, (
        "spawn_sidecar_release must obtain the port by calling parse_server_started on a stdout line"
    )


# ─── Test 7: no real process spawn (mocked AppHandle/ShellExt) ────────


def test_this_test_file_does_not_spawn_processes() -> None:
    """This test file must NOT spawn any real process.

    The Tauri ``AppHandle`` / ``tauri_plugin_shell::ShellExt`` APIs
    are mocked by treating them as opaque: the tests above only read
    the Rust source code as text and assert on its contents. No
    ``subprocess.Popen``, ``os.exec*``, ``os.system``, ``os.spawn*``,
    or ``tauri::AppHandle`` is constructed at runtime.

    We use ``ast`` to parse this file and assert no ``Call`` node
    invokes any forbidden process-spawning API. (String literals in
    docstrings / forbidden_apis lists are NOT calls — the AST check
    avoids false positives on the docstring examples above.)
    """
    import ast

    this_source = _THIS_FILE.read_text(encoding="utf-8")
    tree = ast.parse(this_source)

    # Fully-qualified names of forbidden call targets.
    forbidden_call_names = {
        ("subprocess", "Popen"),
        ("subprocess", "run"),
        ("subprocess", "call"),
        ("subprocess", "check_call"),
        ("subprocess", "check_output"),
        ("os", "system"),
        ("os", "popen"),
        ("os", "spawnl"),
        ("os", "spawnle"),
        ("os", "spawnlp"),
        ("os", "spawnlpe"),
        ("os", "spawnv"),
        ("os", "spawnve"),
        ("os", "spawnvp"),
        ("os", "spawnvpe"),
        ("os", "execl"),
        ("os", "execle"),
        ("os", "execlp"),
        ("os", "execlpe"),
        ("os", "execv"),
        ("os", "execve"),
        ("os", "execvp"),
        ("os", "execvpe"),
    }

    def _qualified(node: ast.AST) -> tuple[str, ...] | None:
        """Return the dotted call target of `node`, or None."""
        if isinstance(node, ast.Attribute):
            base = _qualified(node.value)
            if base is None:
                return None
            return base + (node.attr,)
        if isinstance(node, ast.Name):
            return (node.id,)
        return None

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        target = _qualified(node.func)
        if target is None:
            continue
        for forbidden in forbidden_call_names:
            if tuple(target[-len(forbidden) :]) == forbidden:
                pytest.fail(
                    f"This test file must NOT call {'.'.join(forbidden)}() — "
                    f"the tauri::AppHandle / tauri_plugin_shell APIs are "
                    f"mocked by static source inspection. No real sidecar "
                    f"process may be spawned in the sandbox."
                )


def test_spawn_rs_uses_app_handle_not_concrete_process(spawn_rs_source) -> None:
    """The release-path spawn takes a ``&tauri::AppHandle`` (mockable).

    spawn_sidecar_release's signature is
    ``(app: &tauri::AppHandle, token: &str) -> Result<...>``. The
    ``AppHandle`` is a trait object that can be substituted with a
    mock in Rust unit tests (e.g. via ``mockall`` or a test double).
    The function does NOT directly construct a ``std::process::Command``
    — it goes through ``app.shell().sidecar(...).spawn()`` which is
    the mockable plugin boundary.
    """
    assert re.search(
        r"fn\s+spawn_sidecar_release\s*\(\s*app\s*:\s*&tauri::AppHandle",
        spawn_rs_source,
    ), (
        "spawn_sidecar_release must take `app: &tauri::AppHandle` as the "
        "first arg (mockable plugin boundary, not a concrete process)"
    )
    assert re.search(
        r"fn\s+spawn_sidecar_and_get_port\s*\(\s*app\s*:\s*&tauri::AppHandle",
        spawn_rs_source,
    ), "spawn_sidecar_and_get_port must take `app: &tauri::AppHandle` (the public entry point)"


# ─── Test 8 (bonus): dev-mode fallback path is wired (ADR-0020 §14) ───


def test_spawn_rs_has_dev_mode_fallback(spawn_rs_source) -> None:
    """ADR-0020 §14: spawn.rs must have a dev-mode fallback path.

    When ``VOICE_TYPER_SIDECAR_DEV=1`` is set, the host spawns
    ``python -m voice_typer.server.ipc_server --ws`` via
    ``tokio::process::Command`` instead of the frozen externalBin.
    This lets UI/transport iterate in seconds (no Nuitka recompile)
    during dev. The release path (this gate check's scope) is the
    frozen-exe path; the dev path is verified here only as a code
    branch that exists.
    """
    assert "fn is_dev_mode" in spawn_rs_source, (
        "spawn.rs must define `is_dev_mode()` to check VOICE_TYPER_SIDECAR_DEV=1"
    )
    assert "fn spawn_sidecar_dev_mode" in spawn_rs_source, (
        "spawn.rs must define `spawn_sidecar_dev_mode` for the dev fallback"
    )
    # The dev-mode path must use tokio::process::Command (NOT the shell plugin).
    assert "tokio::process::Command" in spawn_rs_source, (
        "spawn_sidecar_dev_mode must use tokio::process::Command (not the "
        "tauri-plugin-shell) — dev mode bypasses externalBin"
    )
    # The dev-mode Python binary name must be platform-correct.
    assert re.search(
        r'cfg!\s*\(\s*target_os\s*=\s*"windows"\s*\)',
        spawn_rs_source,
    ), (
        'spawn_sidecar_dev_mode must use cfg!(target_os = "windows") to '
        "pick python.exe on Windows vs python3 on macOS/Linux"
    )


# ─── Test 9 (bonus): server_started timeout matches ADR-0020 §1 ──────


def test_server_started_timeout_is_30s(util_rs_source) -> None:
    """ADR-0020 §1: the host waits up to 30 s for server_started.

    The sidecar must emit the ``server_started`` JSON within 30 s of
    spawn — if it doesn't, the host kills the child and reports the
    failure (runbook §6.1 fail-scenario: "sidecar did not emit
    server_started within 30000ms").
    """
    timeout_re = re.compile(r"const\s+SERVER_STARTED_TIMEOUT_MS\s*:\s*u64\s*=\s*([\d_]+)")
    m = timeout_re.search(util_rs_source)
    assert m, "util.rs must define SERVER_STARTED_TIMEOUT_MS"
    # Rust allows `30_000` as a digit-separator literal — strip underscores.
    timeout_ms = int(m.group(1).replace("_", ""))
    assert timeout_ms == 30_000, (
        f"SERVER_STARTED_TIMEOUT_MS must be 30000 (30 s), got {timeout_ms}; "
        f"ADR-0020 §1 + runbook §6.1 fail-scenario message"
    )
